name: Manual Beta ISO Builder

on:
  workflow_dispatch: # Manual trigger

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant write permission for releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for changelog generation

      - name: Build ISO in Docker (privileged)
        run: |
          docker run --rm --privileged -v "${{ github.workspace }}":/build -w /build archlinux:base /bin/bash -c "
            pacman -Sy --noconfirm archiso git &&
            git clone https://github.com/minhmc2007/Blue-Archive-Linux &&
            cd Blue-Archive-Linux/blue_archive_linux &&
            bash build.sh
          "

      - name: Copy ISO from build output
        run: |
          mkdir -p output
          cp -r Blue-Archive-Linux/blue_archive_linux/out/* output/ || echo 'No ISO output found'

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BlueArchiveLinux
          path: output/

      - name: Get ISO filename
        id: get_iso
        run: |
          ISO_FILE=$(ls output/*.iso | head -n 1)
          if [ -z "$ISO_FILE" ]; then
            echo "No ISO file found in output/ directory. Skipping release upload."
            echo "iso_file=" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "iso_file=$ISO_FILE" >> $GITHUB_OUTPUT

      - name: Get previous release tag
        id: get_prev_tag
        run: |
          PREV_TAG=$(git tag --sort=-version:refname | grep -E '^nightly-build-' | head -n 1)
          if [ -z "$PREV_TAG" ]; then
            echo "No previous nightly build tag found. Using first commit."
            PREV_TAG=$(git rev-list --max-parents=0 HEAD)
          fi
          echo "prev_tag=$PREV_TAG" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          PREV_TAG="${{ steps.get_prev_tag.outputs.prev_tag }}"
          
          # Generate changelog using git log
          CHANGELOG=$(git log --pretty=format:"- %s (%h)" $PREV_TAG..HEAD --no-merges)
          
          # If no changes, create a simple message
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="- No new commits since last release"
          fi
          
          # Create full changelog with metadata
          FULL_CHANGELOG=$(cat << 'EOF'
## 🚀 Nightly Build ${{ github.run_id }}

### 📋 Build Information
- **Build Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
- **Workflow Run**: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
- **Commit**: [\`$(git rev-parse --short HEAD)\`](${{ github.server_url }}/${{ github.repository }}/commit/$(git rev-parse HEAD))
- **Branch**: ${{ github.ref_name }}

### 📝 Changes Since Last Release
$CHANGELOG

### 💾 Download
- Download the ISO file from the assets below
- This is an automated nightly build and may contain experimental features

---
*This release was automatically generated by GitHub Actions*
EOF
          )
          
          # Save changelog to file
          echo "$FULL_CHANGELOG" > changelog.md
          
          # Write to GitHub output with proper multi-line handling
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$FULL_CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create or Update Release and Upload ISO
        if: steps.get_iso.outputs.iso_file != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: nightly-build-${{ github.run_id }}-${{ github.run_attempt }}
          name: Nightly Build ${{ github.run_id }} (Attempt ${{ github.run_attempt }})
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: true
          files: ${{ steps.get_iso.outputs.iso_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
